--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_BOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DVD_MOVIE
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_DVD_MOVIE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DVD_USER
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_DVD_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NURI_CHANNEL
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_NURI_CHANNEL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPLY
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_REPLY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RMBOARD
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_RMBOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SCORE
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA_WEB2"."SEQ_SCORE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."BOARD" 
   (	"BOARD_NO" NUMBER(10,0), 
	"WRITER" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"VIEW_CNT" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DVD_MOVIE
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."DVD_MOVIE" 
   (	"SERIAL_NUMBER" NUMBER(10,0), 
	"MOVIE_NAME" VARCHAR2(50 BYTE), 
	"NATION" VARCHAR2(20 BYTE), 
	"PUB_YEAR" CHAR(4 BYTE), 
	"CHARGE" NUMBER(5,0), 
	"RENTAL" CHAR(1 BYTE) DEFAULT 'F', 
	"USER_NUMBER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DVD_USER
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."DVD_USER" 
   (	"USER_NUMBER" NUMBER(10,0), 
	"USER_NAME" VARCHAR2(10 BYTE), 
	"PHONE_NUMBER" VARCHAR2(13 BYTE), 
	"TOTAL_PAYING" NUMBER(10,0) DEFAULT 0, 
	"GRADE" VARCHAR2(10 BYTE) DEFAULT 'BRONZE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."MEMBER" 
   (	"ACCOUNT" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"AUTH" VARCHAR2(20 BYTE) DEFAULT 'COMMON', 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"SESSION_ID" VARCHAR2(200 BYTE) DEFAULT 'none', 
	"LIMIT_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NURI_CHANNEL
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."NURI_CHANNEL" 
   (	"CHANNEL_NO" NUMBER(10,0), 
	"CHANNEL_NAME" VARCHAR2(20 BYTE), 
	"CHANNEL_INFO" VARCHAR2(100 BYTE), 
	"ADMIN_USER_NO" NUMBER(10,0), 
	"CHANNEL_PW" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RMBOARD
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."RMBOARD" 
   (	"RES_NUM" NUMBER(10,0), 
	"RES_NAME" VARCHAR2(50 BYTE), 
	"TEL_NUMBER" VARCHAR2(50 BYTE), 
	"MENUS" VARCHAR2(2000 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SCORE
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."SCORE" 
   (	"STU_NUM" NUMBER(10,0), 
	"STU_NAME" VARCHAR2(20 BYTE), 
	"KOR" NUMBER(3,0), 
	"ENG" NUMBER(3,0), 
	"MATH" NUMBER(3,0), 
	"TOTAL" NUMBER(3,0), 
	"AVERAGE" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_REPLY
--------------------------------------------------------

  CREATE TABLE "JAVA_WEB2"."TBL_REPLY" 
   (	"REPLY_NO" NUMBER(10,0), 
	"BOARD_NO" NUMBER(10,0), 
	"REPLY_TEXT" VARCHAR2(1000 BYTE), 
	"REPLY_WRITER" VARCHAR2(50 BYTE), 
	"REPLY_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JAVA_WEB2.BOARD
SET DEFINE OFF;
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (21,'USER1','테스트제목1','테스트 내용입니다.1',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (8,'수정 ','수정 testㅇㅁㅇㄴㄹㅇ','ㅁㄴㅇㄻㅇㅎfkljkasd
ㅇ
ㄹ
ㅁㅇㄴ

',4);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (12,'ㅠㅠ','아아 어렵다 ㅠㅜ123','ㅁ니아러ㅣ마언리ㅏㅁㅇ
ㅁㅇ너라ㅣ멍ㄴ리ㅏㅁ
머나이러마ㅣㅇ너라ㅣㅁ',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (11,'김나나','안녕하세요','ㅁㄴㅇ
ㄹ
ㅁㅇㄴ
ㄹ
ㅁㅇㄹ
',2);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (13,'으아아아','맵퍼 다시 테스트','ㅠㅜㅠㅜㅠㅜㅁ''류
ㅇㅁ
ㄹ
ㅁㅇ
ㄻ
ㅇㄹ
',2);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (22,'USER2','테스트제목2','테스트 내용입니다.2',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (23,'USER3','테스트제목3','테스트 내용입니다.3',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (24,'USER4','테스트제목4','테스트 내용입니다.4',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (25,'USER5','테스트제목5','테스트 내용입니다.5',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (26,'USER6','테스트제목6','테스트 내용입니다.6',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (27,'USER7','테스트제목7','테스트 내용입니다.7',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (28,'USER8','테스트제목8','테스트 내용입니다.8',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (29,'USER9','테스트제목9','테스트 내용입니다.9',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (30,'USER10','테스트제목10','테스트 내용입니다.10',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (31,'USER11','테스트제목11','테스트 내용입니다.11',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (32,'USER12','테스트제목12','테스트 내용입니다.12',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (33,'USER13','테스트제목13','테스트 내용입니다.13',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (34,'USER14','테스트제목14','테스트 내용입니다.14',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (35,'USER15','테스트제목15','테스트 내용입니다.15',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (36,'USER16','테스트제목16','테스트 내용입니다.16',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (37,'USER17','테스트제목17','테스트 내용입니다.17',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (38,'USER18','테스트제목18','테스트 내용입니다.18',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (39,'USER19','테스트제목19','테스트 내용입니다.19',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (40,'USER20','테스트제목20','테스트 내용입니다.20',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (41,'USER21','테스트제목21','테스트 내용입니다.21',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (42,'USER22','테스트제목22','테스트 내용입니다.22',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (43,'USER23','테스트제목23','테스트 내용입니다.23',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (44,'USER24','테스트제목24','테스트 내용입니다.24',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (45,'USER25','테스트제목25','테스트 내용입니다.25',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (46,'USER26','테스트제목26','테스트 내용입니다.26',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (47,'USER27','테스트제목27','테스트 내용입니다.27',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (48,'USER28','테스트제목28','테스트 내용입니다.28',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (49,'USER29','테스트제목29','테스트 내용입니다.29',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (50,'USER30','테스트제목30','테스트 내용입니다.30',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (51,'USER31','테스트제목31','테스트 내용입니다.31',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (52,'USER32','테스트제목32','테스트 내용입니다.32',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (53,'USER33','테스트제목33','테스트 내용입니다.33',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (54,'USER34','테스트제목34','테스트 내용입니다.34',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (55,'USER35','테스트제목35','테스트 내용입니다.35',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (56,'USER36','테스트제목36','테스트 내용입니다.36',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (57,'USER37','테스트제목37','테스트 내용입니다.37',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (58,'USER38','테스트제목38','테스트 내용입니다.38',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (59,'USER39','테스트제목39','테스트 내용입니다.39',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (60,'USER40','테스트제목40','테스트 내용입니다.40',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (61,'USER41','테스트제목41','테스트 내용입니다.41',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (62,'USER42','테스트제목42','테스트 내용입니다.42',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (63,'USER43','테스트제목43','테스트 내용입니다.43',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (64,'USER44','테스트제목44','테스트 내용입니다.44',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (65,'USER45','테스트제목45','테스트 내용입니다.45',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (66,'USER46','테스트제목46','테스트 내용입니다.46',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (67,'USER47','테스트제목47','테스트 내용입니다.47',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (68,'USER48','테스트제목48','테스트 내용입니다.48',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (69,'USER49','테스트제목49','테스트 내용입니다.49',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (70,'USER50','테스트제목50','테스트 내용입니다.50',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (71,'USER51','테스트제목51','테스트 내용입니다.51',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (72,'USER52','테스트제목52','테스트 내용입니다.52',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (73,'USER53','테스트제목53','테스트 내용입니다.53',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (74,'USER54','테스트제목54','테스트 내용입니다.54',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (75,'USER55','테스트제목55','테스트 내용입니다.55',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (76,'USER56','테스트제목56','테스트 내용입니다.56',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (77,'USER57','테스트제목57','테스트 내용입니다.57',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (78,'USER58','테스트제목58','테스트 내용입니다.58',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (79,'USER59','테스트제목59','테스트 내용입니다.59',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (80,'USER60','테스트제목60','테스트 내용입니다.60',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (81,'USER61','테스트제목61','테스트 내용입니다.61',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (82,'USER62','테스트제목62','테스트 내용입니다.62',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (83,'USER63','테스트제목63','테스트 내용입니다.63',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (84,'USER64','테스트제목64','테스트 내용입니다.64',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (85,'USER65','테스트제목65','테스트 내용입니다.65',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (86,'USER66','테스트제목66','테스트 내용입니다.66',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (87,'USER67','테스트제목67','테스트 내용입니다.67',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (88,'USER68','테스트제목68','테스트 내용입니다.68',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (89,'USER69','테스트제목69','테스트 내용입니다.69',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (90,'USER70','테스트제목70','테스트 내용입니다.70',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (91,'USER71','테스트제목71','테스트 내용입니다.71',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (92,'USER72','테스트제목72','테스트 내용입니다.72',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (93,'USER73','테스트제목73','테스트 내용입니다.73',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (94,'USER74','테스트제목74','테스트 내용입니다.74',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (95,'USER75','테스트제목75','테스트 내용입니다.75',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (96,'USER76','테스트제목76','테스트 내용입니다.76',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (97,'USER77','테스트제목77','테스트 내용입니다.77',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (98,'USER78','테스트제목78','테스트 내용입니다.78',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (99,'USER79','테스트제목79','테스트 내용입니다.79',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (100,'USER80','테스트제목80','테스트 내용입니다.80',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (101,'USER81','테스트제목81','테스트 내용입니다.81',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (102,'USER82','테스트제목82','테스트 내용입니다.82',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (103,'USER83','테스트제목83','테스트 내용입니다.83',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (104,'USER84','테스트제목84','테스트 내용입니다.84',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (105,'USER85','테스트제목85','테스트 내용입니다.85',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (106,'USER86','테스트제목86','테스트 내용입니다.86',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (107,'USER87','테스트제목87','테스트 내용입니다.87',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (108,'USER88','테스트제목88','테스트 내용입니다.88',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (109,'USER89','테스트제목89','테스트 내용입니다.89',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (110,'USER90','테스트제목90','테스트 내용입니다.90',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (111,'USER91','테스트제목91','테스트 내용입니다.91',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (112,'USER92','테스트제목92','테스트 내용입니다.92',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (113,'USER93','테스트제목93','테스트 내용입니다.93',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (114,'USER94','테스트제목94','테스트 내용입니다.94',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (115,'USER95','테스트제목95','테스트 내용입니다.95',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (116,'USER96','테스트제목96','테스트 내용입니다.96',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (117,'USER97','테스트제목97','테스트 내용입니다.97',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (118,'USER98','테스트제목98','테스트 내용입니다.98',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (119,'USER99','테스트제목99','테스트 내용입니다.99',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (120,'USER100','테스트제목100','테스트 내용입니다.100',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (121,'USER101','테스트제목101','테스트 내용입니다.101',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (122,'USER102','테스트제목102','테스트 내용입니다.102',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (123,'USER103','테스트제목103','테스트 내용입니다.103',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (124,'USER104','테스트제목104','테스트 내용입니다.104',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (125,'USER105','테스트제목105','테스트 내용입니다.105',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (126,'USER106','테스트제목106','테스트 내용입니다.106',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (127,'USER107','테스트제목107','테스트 내용입니다.107',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (128,'USER108','테스트제목108','테스트 내용입니다.108',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (129,'USER109','테스트제목109','테스트 내용입니다.109',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (130,'USER110','테스트제목110','테스트 내용입니다.110',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (131,'USER111','테스트제목111','테스트 내용입니다.111',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (132,'USER112','테스트제목112','테스트 내용입니다.112',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (133,'USER113','테스트제목113','테스트 내용입니다.113',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (134,'USER114','테스트제목114','테스트 내용입니다.114',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (135,'USER115','테스트제목115','테스트 내용입니다.115',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (136,'USER116','테스트제목116','테스트 내용입니다.116',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (137,'USER117','테스트제목117','테스트 내용입니다.117',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (138,'USER118','테스트제목118','테스트 내용입니다.118',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (139,'USER119','테스트제목119','테스트 내용입니다.119',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (140,'USER120','테스트제목120','테스트 내용입니다.120',2);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (141,'USER121','테스트제목121','테스트 내용입니다.121',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (142,'USER122','테스트제목122','테스트 내용입니다.122',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (143,'USER123','테스트제목123','테스트 내용입니다.123',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (144,'USER124','테스트제목124','테스트 내용입니다.124',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (145,'USER125','테스트제목125','테스트 내용입니다.125',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (146,'USER126','테스트제목126','테스트 내용입니다.126',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (147,'USER127','테스트제목127','테스트 내용입니다.127',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (148,'USER128','테스트제목128','테스트 내용입니다.128',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (149,'USER129','테스트제목129','테스트 내용입니다.129',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (150,'USER130','테스트제목130','테스트 내용입니다.130',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (151,'USER131','테스트제목131','테스트 내용입니다.131',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (152,'USER132','테스트제목132','테스트 내용입니다.132',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (153,'USER133','테스트제목133','테스트 내용입니다.133',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (154,'USER134','테스트제목134','테스트 내용입니다.134',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (155,'USER135','테스트제목135','테스트 내용입니다.135',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (156,'USER136','테스트제목136','테스트 내용입니다.136',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (157,'USER137','테스트제목137','테스트 내용입니다.137',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (158,'USER138','테스트제목138','테스트 내용입니다.138',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (159,'USER139','테스트제목139','테스트 내용입니다.139',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (160,'USER140','테스트제목140','테스트 내용입니다.140',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (161,'USER141','테스트제목141','테스트 내용입니다.141',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (162,'USER142','테스트제목142','테스트 내용입니다.142',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (163,'USER143','테스트제목143','테스트 내용입니다.143',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (164,'USER144','테스트제목144','테스트 내용입니다.144',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (165,'USER145','테스트제목145','테스트 내용입니다.145',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (166,'USER146','테스트제목146','테스트 내용입니다.146',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (167,'USER147','테스트제목147','테스트 내용입니다.147',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (168,'USER148','테스트제목148','테스트 내용입니다.148',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (169,'USER149','테스트제목149','테스트 내용입니다.149',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (170,'USER150','테스트제목150','테스트 내용입니다.150',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (171,'USER151','테스트제목151','테스트 내용입니다.151',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (172,'USER152','테스트제목152','테스트 내용입니다.152',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (173,'USER153','테스트제목153','테스트 내용입니다.153',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (174,'USER154','테스트제목154','테스트 내용입니다.154',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (175,'USER155','테스트제목155','테스트 내용입니다.155',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (176,'USER156','테스트제목156','테스트 내용입니다.156',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (177,'USER157','테스트제목157','테스트 내용입니다.157',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (178,'USER158','테스트제목158','테스트 내용입니다.158',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (179,'USER159','테스트제목159','테스트 내용입니다.159',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (180,'USER160','테스트제목160','테스트 내용입니다.160',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (181,'USER161','테스트제목161','테스트 내용입니다.161',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (182,'USER162','테스트제목162','테스트 내용입니다.162',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (183,'USER163','테스트제목163','테스트 내용입니다.163',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (184,'USER164','테스트제목164','테스트 내용입니다.164',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (185,'USER165','테스트제목165','테스트 내용입니다.165',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (186,'USER166','테스트제목166','테스트 내용입니다.166',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (187,'USER167','테스트제목167','테스트 내용입니다.167',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (188,'USER168','테스트제목168','테스트 내용입니다.168',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (189,'USER169','테스트제목169','테스트 내용입니다.169',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (190,'USER170','테스트제목170','테스트 내용입니다.170',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (191,'USER171','테스트제목171','테스트 내용입니다.171',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (192,'USER172','테스트제목172','테스트 내용입니다.172',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (193,'USER173','테스트제목173','테스트 내용입니다.173',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (194,'USER174','테스트제목174','테스트 내용입니다.174',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (195,'USER175','테스트제목175','테스트 내용입니다.175',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (196,'USER176','테스트제목176','테스트 내용입니다.176',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (197,'USER177','테스트제목177','테스트 내용입니다.177',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (198,'USER178','테스트제목178','테스트 내용입니다.178',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (199,'USER179','테스트제목179','테스트 내용입니다.179',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (200,'USER180','테스트제목180','테스트 내용입니다.180',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (201,'USER181','테스트제목181','테스트 내용입니다.181',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (202,'USER182','테스트제목182','테스트 내용입니다.182',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (203,'USER183','테스트제목183','테스트 내용입니다.183',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (204,'USER184','테스트제목184','테스트 내용입니다.184',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (205,'USER185','테스트제목185','테스트 내용입니다.185',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (206,'USER186','테스트제목186','테스트 내용입니다.186',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (207,'USER187','테스트제목187','테스트 내용입니다.187',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (208,'USER188','테스트제목188','테스트 내용입니다.188',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (209,'USER189','테스트제목189','테스트 내용입니다.189',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (210,'USER190','테스트제목190','테스트 내용입니다.190',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (211,'USER191','테스트제목191','테스트 내용입니다.191',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (212,'USER192','테스트제목192','테스트 내용입니다.192',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (213,'USER193','테스트제목193','테스트 내용입니다.193',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (214,'USER194','테스트제목194','테스트 내용입니다.194',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (215,'USER195','테스트제목195','테스트 내용입니다.195',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (216,'USER196','테스트제목196','테스트 내용입니다.196',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (217,'USER197','테스트제목197','테스트 내용입니다.197',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (218,'USER198','테스트제목198','테스트 내용입니다.198',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (219,'USER199','테스트제목199','테스트 내용입니다.199',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (220,'USER200','테스트제목200','테스트 내용입니다.200',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (221,'USER201','테스트제목201','테스트 내용입니다.201',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (222,'USER202','테스트제목202','테스트 내용입니다.202',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (223,'USER203','테스트제목203','테스트 내용입니다.203',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (224,'USER204','테스트제목204','테스트 내용입니다.204',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (225,'USER205','테스트제목205','테스트 내용입니다.205',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (226,'USER206','테스트제목206','테스트 내용입니다.206',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (227,'USER207','테스트제목207','테스트 내용입니다.207',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (228,'USER208','테스트제목208','테스트 내용입니다.208',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (229,'USER209','테스트제목209','테스트 내용입니다.209',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (230,'USER210','테스트제목210','테스트 내용입니다.210',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (231,'USER211','테스트제목211','테스트 내용입니다.211',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (232,'USER212','테스트제목212','테스트 내용입니다.212',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (233,'USER213','테스트제목213','테스트 내용입니다.213',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (234,'USER214','테스트제목214','테스트 내용입니다.214',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (235,'USER215','테스트제목215','테스트 내용입니다.215',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (236,'USER216','테스트제목216','테스트 내용입니다.216',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (237,'USER217','테스트제목217','테스트 내용입니다.217',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (238,'USER218','테스트제목218','테스트 내용입니다.218',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (239,'USER219','테스트제목219','테스트 내용입니다.219',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (240,'USER220','테스트제목220','테스트 내용입니다.220',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (241,'USER221','테스트제목221','테스트 내용입니다.221',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (242,'USER222','테스트제목222','테스트 내용입니다.222',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (243,'USER223','테스트제목223','테스트 내용입니다.223',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (244,'USER224','테스트제목224','테스트 내용입니다.224',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (245,'USER225','테스트제목225','테스트 내용입니다.225',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (246,'USER226','테스트제목226','테스트 내용입니다.226',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (247,'USER227','테스트제목227','테스트 내용입니다.227',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (248,'USER228','테스트제목228','테스트 내용입니다.228',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (249,'USER229','테스트제목229','테스트 내용입니다.229',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (250,'USER230','테스트제목230','테스트 내용입니다.230',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (251,'USER231','테스트제목231','테스트 내용입니다.231',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (252,'USER232','테스트제목232','테스트 내용입니다.232',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (253,'USER233','테스트제목233','테스트 내용입니다.233',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (254,'USER234','테스트제목234','테스트 내용입니다.234',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (255,'USER235','테스트제목235','테스트 내용입니다.235',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (256,'USER236','테스트제목236','테스트 내용입니다.236',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (257,'USER237','테스트제목237','테스트 내용입니다.237',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (258,'USER238','테스트제목238','테스트 내용입니다.238',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (259,'USER239','테스트제목239','테스트 내용입니다.239',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (260,'USER240','테스트제목240','테스트 내용입니다.240',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (261,'USER241','테스트제목241','테스트 내용입니다.241',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (262,'USER242','테스트제목242','테스트 내용입니다.242',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (263,'USER243','테스트제목243','테스트 내용입니다.243',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (264,'USER244','테스트제목244','테스트 내용입니다.244',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (265,'USER245','테스트제목245','테스트 내용입니다.245',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (266,'USER246','테스트제목246','테스트 내용입니다.246',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (267,'USER247','테스트제목247','테스트 내용입니다.247',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (268,'USER248','테스트제목248','테스트 내용입니다.248',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (269,'USER249','테스트제목249','테스트 내용입니다.249',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (270,'USER250','테스트제목250','테스트 내용입니다.250',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (271,'USER251','테스트제목251','테스트 내용입니다.251',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (272,'USER252','테스트제목252','테스트 내용입니다.252',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (273,'USER253','테스트제목253','테스트 내용입니다.253',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (274,'USER254','테스트제목254','테스트 내용입니다.254',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (275,'USER255','테스트제목255','테스트 내용입니다.255',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (276,'USER256','테스트제목256','테스트 내용입니다.256',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (277,'USER257','테스트제목257','테스트 내용입니다.257',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (278,'USER258','테스트제목258','테스트 내용입니다.258',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (279,'USER259','테스트제목259','테스트 내용입니다.259',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (280,'USER260','테스트제목260','테스트 내용입니다.260',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (281,'USER261','테스트제목261','테스트 내용입니다.261',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (282,'USER262','테스트제목262','테스트 내용입니다.262',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (283,'USER263','테스트제목263','테스트 내용입니다.263',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (284,'USER264','테스트제목264','테스트 내용입니다.264',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (285,'USER265','테스트제목265','테스트 내용입니다.265',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (286,'USER266','테스트제목266','테스트 내용입니다.266',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (287,'USER267','테스트제목267','테스트 내용입니다.267',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (288,'USER268','테스트제목268','테스트 내용입니다.268',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (289,'USER269','테스트제목269','테스트 내용입니다.269',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (290,'USER270','테스트제목270','테스트 내용입니다.270',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (291,'USER271','테스트제목271','테스트 내용입니다.271',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (292,'USER272','테스트제목272','테스트 내용입니다.272',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (293,'USER273','테스트제목273','테스트 내용입니다.273',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (294,'USER274','테스트제목274','테스트 내용입니다.274',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (295,'USER275','테스트제목275','테스트 내용입니다.275',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (296,'USER276','테스트제목276','테스트 내용입니다.276',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (297,'USER277','테스트제목277','테스트 내용입니다.277',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (298,'USER278','테스트제목278','테스트 내용입니다.278',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (299,'USER279','테스트제목279','테스트 내용입니다.279',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (300,'USER280','테스트제목280','테스트 내용입니다.280',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (301,'USER281','테스트제목281','테스트 내용입니다.281',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (302,'USER282','테스트제목282','테스트 내용입니다.282',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (303,'USER283','테스트제목283','테스트 내용입니다.283',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (304,'USER284','테스트제목284','테스트 내용입니다.284',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (305,'USER285','테스트제목285','테스트 내용입니다.285',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (306,'USER286','테스트제목286','테스트 내용입니다.286',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (307,'USER287','테스트제목287','테스트 내용입니다.287',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (308,'USER288','테스트제목288','테스트 내용입니다.288',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (309,'USER289','테스트제목289','테스트 내용입니다.289',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (310,'USER290','테스트제목290','테스트 내용입니다.290',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (311,'USER291','테스트제목291','테스트 내용입니다.291',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (312,'USER292','테스트제목292','테스트 내용입니다.292',0);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (313,'USER293','테스트제목293','테스트 내용입니다.293',4);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (314,'USER294','테스트제목294','테스트 내용입니다.294',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (315,'USER295','테스트제목295','테스트 내용입니다.295',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (316,'USER296','테스트제목296','테스트 내용입니다.296',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (317,'USER297','테스트제목297','테스트 내용입니다.297',1);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (318,'USER298','테스트제목298','테스트 내용입니다.298',2);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (319,'USER299','테스트제목299','테스트 내용입니다.299',3);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (320,'USER300','테스트제목300','테스트 내용입니다.300',8);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (321,'멍멍이','테스트','블라블라',2);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (322,'홍길동','글쎄다?','ㅁ
ㅇ
ㅇ
',58);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (323,'banana1}','asdlkfjlk','asdf adsf',8);
Insert into JAVA_WEB2.BOARD (BOARD_NO,WRITER,TITLE,CONTENT,VIEW_CNT) values (324,'banana1','ddfad','adf',11);
REM INSERTING into JAVA_WEB2.DVD_MOVIE
SET DEFINE OFF;
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (1,'인터스텔라','미국','2014',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (2,'포레스트 검프','미국','1994',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (3,'너의 이름은','일본','2017',3000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (4,'라라랜드','미국','2016',2500,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (5,'레옹','프랑스','1994',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (6,'어바웃 타임','영국','2013',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (7,'타이타닉','미국','1998',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (8,'인생은 아름다워','이탈리아','1999',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (9,'쇼생크 탈출','미국','1995',2000,'F',null);
Insert into JAVA_WEB2.DVD_MOVIE (SERIAL_NUMBER,MOVIE_NAME,NATION,PUB_YEAR,CHARGE,RENTAL,USER_NUMBER) values (10,'기생충','대한민국','2019',4000,'F',null);
REM INSERTING into JAVA_WEB2.DVD_USER
SET DEFINE OFF;
Insert into JAVA_WEB2.DVD_USER (USER_NUMBER,USER_NAME,PHONE_NUMBER,TOTAL_PAYING,GRADE) values (1,'김철수','010-1234-9876',0,'BRONZE');
Insert into JAVA_WEB2.DVD_USER (USER_NUMBER,USER_NAME,PHONE_NUMBER,TOTAL_PAYING,GRADE) values (2,'박영희','010-5455-7788',0,'BRONZE');
Insert into JAVA_WEB2.DVD_USER (USER_NUMBER,USER_NAME,PHONE_NUMBER,TOTAL_PAYING,GRADE) values (3,'도우너','010-9988-2525',0,'BRONZE');
Insert into JAVA_WEB2.DVD_USER (USER_NUMBER,USER_NAME,PHONE_NUMBER,TOTAL_PAYING,GRADE) values (4,'고길동','010-9876-2323',0,'BRONZE');
REM INSERTING into JAVA_WEB2.MEMBER
SET DEFINE OFF;
Insert into JAVA_WEB2.MEMBER (ACCOUNT,PASSWORD,NAME,EMAIL,AUTH,REG_DATE,SESSION_ID,LIMIT_TIME) values ('admin','1234','관리자','admin@gmail.com','ADMIN',to_date('21/06/02 13:07:12','RR/MM/DD HH24:MI:SS'),'none',null);
Insert into JAVA_WEB2.MEMBER (ACCOUNT,PASSWORD,NAME,EMAIL,AUTH,REG_DATE,SESSION_ID,LIMIT_TIME) values ('abc4321','aaa1234','고길동','aaa4343@gmail.com','COMMON',to_date('21/06/02 13:35:14','RR/MM/DD HH24:MI:SS'),'none',null);
Insert into JAVA_WEB2.MEMBER (ACCOUNT,PASSWORD,NAME,EMAIL,AUTH,REG_DATE,SESSION_ID,LIMIT_TIME) values ('banana','$2a$10$u6VUI/Ph5L8YPeHZjikrruNM/kWuUkQzV62Kqldah4MPG.ZW8yUbe','김나나','bbb2222@naver.com','COMMON',to_date('21/06/02 14:10:22','RR/MM/DD HH24:MI:SS'),'none',null);
Insert into JAVA_WEB2.MEMBER (ACCOUNT,PASSWORD,NAME,EMAIL,AUTH,REG_DATE,SESSION_ID,LIMIT_TIME) values ('test1111','$2a$10$haYA1fpBP5EzY38A3chSVuCHRrd/S.T1bMkbUCbozAJUTI0S13kpy','test11','test1111@isec.com','COMMON',to_date('21/06/02 15:26:29','RR/MM/DD HH24:MI:SS'),'none',to_date('21/06/04 15:42:36','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.MEMBER (ACCOUNT,PASSWORD,NAME,EMAIL,AUTH,REG_DATE,SESSION_ID,LIMIT_TIME) values ('banana1','$2a$10$XPaNoPNktKm4kG.6H4WvxuuFeXsyD9W4E/uw8gW9x9YNPUwoPiGOG','바나나','banana1@isec.com','COMMON',to_date('21/06/03 13:12:38','RR/MM/DD HH24:MI:SS'),'none',to_date('21/06/04 15:44:13','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.MEMBER (ACCOUNT,PASSWORD,NAME,EMAIL,AUTH,REG_DATE,SESSION_ID,LIMIT_TIME) values ('admin123','$2a$10$ApDGY5w5JYZLWifokRDBE.9jIK9G1DnuexKadTUON7cQoNq9qMBdm','박관리자','admin123@naver.com','ADMIN',to_date('21/06/03 14:45:57','RR/MM/DD HH24:MI:SS'),'none',null);
REM INSERTING into JAVA_WEB2.NURI_CHANNEL
SET DEFINE OFF;
REM INSERTING into JAVA_WEB2.RMBOARD
SET DEFINE OFF;
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (56,'매점명1','연락처1','테스트 내용 블라블라1','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (106,'매점명1','연락처1','테스트 내용 블라블라1','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (58,'매점명3','연락처3','테스트 내용 블라블라3','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (59,'매점명4','연락처4','테스트 내용 블라블라4','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (107,'매점명2','연락처2','테스트 내용 블라블라2','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (61,'매점명6','연락처6','테스트 내용 블라블라6','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (62,'매점명7','연락처7','테스트 내용 블라블라7','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (63,'매점명8','연락처8','테스트 내용 블라블라8','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (64,'매점명9','연락처9','테스트 내용 블라블라9','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (65,'매점명10','연락처10','테스트 내용 블라블라10','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (66,'매점명11','연락처11','테스트 내용 블라블라11','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (67,'매점명12','연락처12','테스트 내용 블라블라12','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (68,'매점명13','연락처13','테스트 내용 블라블라13','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (69,'매점명14','연락처14','테스트 내용 블라블라14','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (70,'매점명15','연락처15','테스트 내용 블라블라15','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (71,'매점명16','연락처16','테스트 내용 블라블라16','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (72,'매점명17','연락처17','테스트 내용 블라블라17','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (108,'매점명3','연락처3','테스트 내용 블라블라3','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (74,'매점명19','연락처19','테스트 내용 블라블라19','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (75,'매점명20444','연락처20444','테스트 내용 블라블라20','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (76,'매점명21','연락처21','테스트 내용 블라블라21','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (77,'매점명22','연락처22','테스트 내용 블라블라22','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (78,'매점명23','연락처23','테스트 내용 블라블라23','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (79,'매점명24 asdfasd','연락처24','테스트 내용 블라블라24','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (80,'매점명25','연락처25','테스트 내용 블라블라25','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (81,'매점명26','연락처26','테스트 내용 블라블라26','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (82,'매점명27','연락처27','테스트 내용 블라블라27','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (83,'매점명28','연락처28','테스트 내용 블라블라28','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (84,'매점명29','연락처29','테스트 내용 블라블라29','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (85,'매점명30','연락처30','테스트 내용 블라블라30','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (87,'매점명32','연락처32','테스트 내용 블라블라32','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (88,'매점명33','연락처33','테스트 내용 블라블라33','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (89,'매점명34','연락처34','테스트 내용 블라블라34','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (90,'매점명35','연락처35','테스트 내용 블라블라35','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (91,'매점명36','연락처36','테스트 내용 블라블라36df','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (92,'매점명37','연락처37','테스트 내용 블라블라37','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (93,'매점명38','연락처38','테스트 내용 블라블라38','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (94,'매점명39','연락처39','테스트 내용 블라블라39','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (95,'매점명40 test','연락처40','테스트 내용 블라블라40','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (96,'매점명41','연락처41','테스트 내용 블라블라41','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (97,'매점명42','연락처42','테스트 내용 블라블라42','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (98,'매점명43 ttt','연락처43','테스트 내용 블라블라43','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (99,'매점명44','연락처44','테스트 내용 블라블라44','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (100,'매점명45','연락처45','테스트 내용 블라블라45','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (101,'매점명46','연락처46','테스트 내용 블라블라46','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (102,'매점명47 ttttt','연락처47','테스트 내용 블라블라47','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (103,'매점명48','연락처48333','테스트 내용 블라블라48dfasdfa','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (104,'매점명49','연락처49','테스트 내용 블라블라49','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (109,'매점명4','연락처4','테스트 내용 블라블라4','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (110,'매점명5','연락처5','테스트 내용 블라블라5','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (111,'매점명6','연락처6','테스트 내용 블라블라6','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (112,'매점명7','연락처7','테스트 내용 블라블라7','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (113,'매점명8','연락처8','테스트 내용 블라블라8','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (114,'매점명9','연락처9','테스트 내용 블라블라9','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (115,'매점명10','연락처10','테스트 내용 블라블라10','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (116,'매점명11','연락처11','테스트 내용 블라블라11','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (117,'매점명12','연락처12','테스트 내용 블라블라12','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (118,'매점명13','연락처13','테스트 내용 블라블라13','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (119,'매점명14','연락처14','테스트 내용 블라블라14','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (120,'매점명15','연락처15','테스트 내용 블라블라15','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (121,'매점명16','연락처16','테스트 내용 블라블라16','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (122,'매점명17','연락처17','테스트 내용 블라블라17','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (123,'매점명18','연락처18','테스트 내용 블라블라18','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (124,'매점명19','연락처19','테스트 내용 블라블라19','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (125,'매점명20','연락처20','테스트 내용 블라블라20','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (126,'매점명21','연락처21','테스트 내용 블라블라21','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (128,'매점명23 tttt','연락처23','테스트 내용 블라블라23','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (129,'매점명24','연락처24','테스트 내용 블라블라24','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (130,'매점명25','연락처25','테스트 내용 블라블라25','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (131,'매점명26','연락처26','테스트 내용 블라블라26','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (132,'매점명27','연락처27','테스트 내용 블라블라27','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (133,'매점명28','연락처28','테스트 내용 블라블라28','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (134,'매점명29','연락처29','테스트 내용 블라블라29','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (135,'매점명30 46346','연락처30','테스트 내용 블라블라30','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (136,'매점명31','연락처31','테스트 내용 블라블라31','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (137,'매점명32','연락처32','테스트 내용 블라블라32','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (138,'매점명33','연락처33','테스트 내용 블라블라33','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (139,'매점명34','연락처34','테스트 내용 블라블라34','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (140,'매점명35','연락처35','테스트 내용 블라블라35','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (141,'매점명36','연락처36','테스트 내용 블라블라36','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (142,'매점명37','연락처37','테스트 내용 블라블라37','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (143,'매점명38','연락처38','테스트 내용 블라블라38','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (144,'매점명39','연락처39','테스트 내용 블라블라39','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (145,'매점명40','연락처40','테스트 내용 블라블라40uigtighk','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (146,'매점명41','연락처41','테스트 내용 블라블라41','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (147,'매점명42','연락처42','테스트 내용 블라블라42','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (148,'매점명43','연락처43','테스트 내용 블라블라43','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (149,'매점명44','연락처44','테스트 내용 블라블라44','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (150,'매점명45','연락처45','테스트 내용 블라블라45','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (151,'매점명46','연락처46','테스트 내용 블라블라46','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (152,'매점명47','연락처47','테스트 내용 블라블라47','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (153,'매점명48','연락처48','테스트 내용 블라블라48','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (154,'매점명49','연락처49','테스트 내용 블라블라49','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (155,'매점명50','연락처50','테스트 내용 블라블라50','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (156,'매점명1','연락처1','테스트 내용 블라블라1','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (157,'매점명2','연락처2','테스트 내용 블라블라2','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (158,'매점명3','연락처3','테스트 내용 블라블라3','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (159,'매점명4','연락처4','테스트 내용 블라블라4','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (160,'매점명5','연락처5','테스트 내용 블라블라5','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (161,'매점명6','연락처6','테스트 내용 블라블라6','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (162,'매점명7','연락처7','테스트 내용 블라블라7','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (163,'매점명8','연락처8','테스트 내용 블라블라8','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (164,'매점명9','연락처9','테스트 내용 블라블라9','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (165,'매점명10','연락처10','테스트 내용 블라블라10','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (166,'매점명11','연락처11','테스트 내용 블라블라11','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (167,'매점명12','연락처12','테스트 내용 블라블라12','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (168,'매점명13','연락처13','테스트 내용 블라블라13','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (169,'매점명14','연락처14','테스트 내용 블라블라14','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (170,'매점명15','연락처15','테스트 내용 블라블라15','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (171,'매점명16','연락처16','테스트 내용 블라블라16','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (172,'매점명17','연락처17','테스트 내용 블라블라17','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (173,'매점명18','연락처18','테스트 내용 블라블라18','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (174,'매점명19','연락처19','테스트 내용 블라블라19','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (175,'매점명20','연락처20','테스트 내용 블라블라20','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (176,'매점명21','연락처21','테스트 내용 블라블라21','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (177,'매점명22','연락처22','테스트 내용 블라블라22','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (178,'매점명23','연락처23','테스트 내용 블라블라23','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (179,'매점명24','연락처24','테스트 내용 블라블라24','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (180,'매점명25','연락처25','테스트 내용 블라블라25','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (181,'매점명26','연락처26','테스트 내용 블라블라26','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (182,'매점명27','연락처27','테스트 내용 블라블라27','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (183,'매점명28','연락처28','테스트 내용 블라블라28','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (184,'매점명29','연락처29','테스트 내용 블라블라29','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (185,'매점명30','연락처30','테스트 내용 블라블라30','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (186,'매점명31','연락처31','테스트 내용 블라블라31','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (187,'매점명32','연락처32','테스트 내용 블라블라32','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (188,'매점명33','연락처33','테스트 내용 블라블라33','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (189,'매점명34','연락처34','테스트 내용 블라블라34','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (190,'매점명35','연락처35','테스트 내용 블라블라35','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (191,'매점명36','연락처36','테스트 내용 블라블라36','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (192,'매점명37','연락처37','테스트 내용 블라블라37','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (193,'매점명38','연락처38','테스트 내용 블라블라38','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (194,'매점명39','연락처39','테스트 내용 블라블라39','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (195,'매점명40','연락처40','테스트 내용 블라블라40','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (196,'매점명41','연락처41','테스트 내용 블라블라41','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (197,'매점명42','연락처42','테스트 내용 블라블라42','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (198,'매점명43','연락처43','테스트 내용 블라블라43','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (199,'매점명44','연락처44','테스트 내용 블라블라44','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (200,'매점명45','연락처45','테스트 내용 블라블라45','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (201,'매점명46','연락처46','테스트 내용 블라블라46','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (202,'매점명47','연락처47','테스트 내용 블라블라47','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (203,'매점명48','연락처48','테스트 내용 블라블라48','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (204,'매점명49','연락처49','테스트 내용 블라블라49','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (205,'매점명50','연락처50','테스트 내용 블라블라50','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (206,'매점명51','연락처51','테스트 내용 블라블라51','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (207,'매점명52','연락처52','테스트 내용 블라블라52','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (208,'매점명53','연락처53','테스트 내용 블라블라53','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (209,'매점명54','연락처54','테스트 내용 블라블라54','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (210,'매점명55','연락처55','테스트 내용 블라블라55','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (211,'매점명56','연락처56','테스트 내용 블라블라56','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (212,'매점명57','연락처57','테스트 내용 블라블라57','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (213,'매점명58','연락처58','테스트 내용 블라블라58','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (214,'매점명59','연락처59','테스트 내용 블라블라59','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (215,'매점명60','연락처60','테스트 내용 블라블라60','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (216,'매점명61','연락처61','테스트 내용 블라블라61','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (217,'매점명62','연락처62','테스트 내용 블라블라62','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (218,'매점명63','연락처63','테스트 내용 블라블라63','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (219,'매점명64','연락처64','테스트 내용 블라블라64','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (220,'매점명65','연락처65','테스트 내용 블라블라65','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (221,'매점명66','연락처66','테스트 내용 블라블라66','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (222,'매점명67','연락처67','테스트 내용 블라블라67','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (223,'매점명68','연락처68','테스트 내용 블라블라68','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (224,'매점명69','연락처69','테스트 내용 블라블라69','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (225,'매점명70','연락처70','테스트 내용 블라블라70','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (226,'매점명71','연락처71','테스트 내용 블라블라71','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (227,'매점명72','연락처72','테스트 내용 블라블라72','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (228,'매점명73','연락처73','테스트 내용 블라블라73','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (229,'매점명74','연락처74 445','테스트 내용 블라블라74','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (230,'매점명75','연락처75','테스트 내용 블라블라75','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (231,'매점명76','연락처76','테스트 내용 블라블라76','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (232,'매점명77','연락처77','테스트 내용 블라블라77','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (233,'매점명78','연락처78','테스트 내용 블라블라78','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (234,'매점명79','연락처79','테스트 내용 블라블라79','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (235,'매점명80','연락처80','테스트 내용 블라블라80','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (236,'매점명81','연락처81','테스트 내용 블라블라81','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (237,'매점명82','연락처82','테스트 내용 블라블라82','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (238,'매점명83','연락처83','테스트 내용 블라블라83','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (239,'매점명84','연락처84','테스트 내용 블라블라84','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (240,'매점명85','연락처85','테스트 내용 블라블라85','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (241,'매점명86','연락처86','테스트 내용 블라블라86','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (242,'매점명87','연락처87','테스트 내용 블라블라87','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (243,'매점명88','연락처88','테스트 내용 블라블라88','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (244,'매점명89','연락처89','테스트 내용 블라블라89','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (245,'매점명90','연락처90','테스트 내용 블라블라90','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (246,'매점명91','연락처91','테스트 내용 블라블라91','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (247,'매점명92','연락처92','테스트 내용 블라블라92','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (248,'매점명93','연락처93','테스트 내용 블라블라93','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (249,'매점명94','연락처94','테스트 내용 블라블라94','CHINA_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (250,'매점명95','연락처95','테스트 내용 블라블라95','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (251,'매점명96','연락처96','테스트 내용 블라블라96','KOREAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (253,'매점명98','연락처98','테스트 내용 블라블라98','ITALY_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (254,'매점명99','연락처99','테스트 내용 블라블라99','JAPAN_FOOD');
Insert into JAVA_WEB2.RMBOARD (RES_NUM,RES_NAME,TEL_NUMBER,MENUS,CATEGORY) values (255,'매점명100','연락처100','테스트 내용 블라블라100','ITALY_FOOD');
REM INSERTING into JAVA_WEB2.SCORE
SET DEFINE OFF;
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (7,'이순신',95,85,70,250,83.35);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (24,'tester',60,30,80,170,56.65);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (21,'tester',50,10,30,90,30);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (4,'홍길동',95,80,70,245,81.65);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (9,'김나나',90,85,95,270,90);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (27,'테스트',90,80,70,240,80);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (22,'김바보',50,60,70,180,60);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (23,'레스트',90,80,60,230,76.65);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (25,'홍길동',50,60,70,180,60);
Insert into JAVA_WEB2.SCORE (STU_NUM,STU_NAME,KOR,ENG,MATH,TOTAL,AVERAGE) values (26,'홍길동',50,60,70,180,60);
REM INSERTING into JAVA_WEB2.TBL_REPLY
SET DEFINE OFF;
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (1,322,'테스트 댓글0444','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (2,322,'홍홍홍','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (3,322,'테스트 댓글2','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (4,322,'테스트 댓글3','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (8,322,'테스트 댓글7','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (9,322,'테스트 댓글8','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (11,322,'테스트 댓글10','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (13,322,'테스트 댓글12','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (14,322,'테스트 댓글13','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (25,322,'댓글 테스트','콩콩',to_date('21/06/01 13:27:57','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (16,322,'테스트 댓글15','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (17,322,'테스트 댓글16','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (18,322,'테스트 댓글17','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (19,322,'테스트 댓글18','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (20,322,'API 댓글 수정 테스트 홍홍','야옹이',to_date('21/05/26 14:34:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (23,321,'API 댓글 테스트 블라블라','콩콩이',to_date('21/05/26 15:35:06','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (24,313,'ㅌㅇㄹ','ㅇㄹㅇㅁ',to_date('21/06/01 13:25:29','RR/MM/DD HH24:MI:SS'));
Insert into JAVA_WEB2.TBL_REPLY (REPLY_NO,BOARD_NO,REPLY_TEXT,REPLY_WRITER,REPLY_DATE) values (26,322,'코오콩','콩콩',to_date('21/06/01 13:29:29','RR/MM/DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_BOARD" ON "JAVA_WEB2"."BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DVD_MOVIE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_DVD_MOVIE" ON "JAVA_WEB2"."DVD_MOVIE" ("SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_MEMBER" ON "JAVA_WEB2"."MEMBER" ("ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NURI_CHANNEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_NURI_CHANNEL" ON "JAVA_WEB2"."NURI_CHANNEL" ("CHANNEL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_REPLY" ON "JAVA_WEB2"."TBL_REPLY" ("REPLY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RMBOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_RMBOARD" ON "JAVA_WEB2"."RMBOARD" ("RES_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SCORE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_SCORE" ON "JAVA_WEB2"."SCORE" ("STU_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USER_NUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_USER_NUMBER" ON "JAVA_WEB2"."DVD_USER" ("USER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007166
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."SYS_C007166" ON "JAVA_WEB2"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_BOARD" ON "JAVA_WEB2"."BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DVD_MOVIE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_DVD_MOVIE" ON "JAVA_WEB2"."DVD_MOVIE" ("SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USER_NUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_USER_NUMBER" ON "JAVA_WEB2"."DVD_USER" ("USER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_MEMBER" ON "JAVA_WEB2"."MEMBER" ("ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007166
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."SYS_C007166" ON "JAVA_WEB2"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NURI_CHANNEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_NURI_CHANNEL" ON "JAVA_WEB2"."NURI_CHANNEL" ("CHANNEL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RMBOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_RMBOARD" ON "JAVA_WEB2"."RMBOARD" ("RES_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SCORE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_SCORE" ON "JAVA_WEB2"."SCORE" ("STU_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA_WEB2"."PK_REPLY" ON "JAVA_WEB2"."TBL_REPLY" ("REPLY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DVD_MOVIE
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."DVD_MOVIE" ADD CONSTRAINT "PK_DVD_MOVIE" PRIMARY KEY ("SERIAL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."DVD_MOVIE" MODIFY ("CHARGE" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."DVD_MOVIE" MODIFY ("PUB_YEAR" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."DVD_MOVIE" MODIFY ("NATION" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."DVD_MOVIE" MODIFY ("MOVIE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DVD_USER
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."DVD_USER" ADD CONSTRAINT "PK_USER_NUMBER" PRIMARY KEY ("USER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."DVD_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."MEMBER" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NURI_CHANNEL
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."NURI_CHANNEL" ADD CONSTRAINT "PK_NURI_CHANNEL" PRIMARY KEY ("CHANNEL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."NURI_CHANNEL" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."NURI_CHANNEL" MODIFY ("ADMIN_USER_NO" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."NURI_CHANNEL" MODIFY ("CHANNEL_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RMBOARD
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."RMBOARD" ADD CONSTRAINT "PK_RMBOARD" PRIMARY KEY ("RES_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."RMBOARD" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."RMBOARD" MODIFY ("TEL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."RMBOARD" MODIFY ("RES_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCORE
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."SCORE" ADD CONSTRAINT "PK_SCORE" PRIMARY KEY ("STU_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."SCORE" MODIFY ("MATH" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."SCORE" MODIFY ("ENG" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."SCORE" MODIFY ("KOR" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."SCORE" MODIFY ("STU_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_REPLY
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."TBL_REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA_WEB2"."TBL_REPLY" MODIFY ("REPLY_WRITER" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."TBL_REPLY" MODIFY ("REPLY_TEXT" NOT NULL ENABLE);
  ALTER TABLE "JAVA_WEB2"."TBL_REPLY" MODIFY ("BOARD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DVD_MOVIE
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."DVD_MOVIE" ADD CONSTRAINT "FK_DVD_MOVIE_DVD_USER" FOREIGN KEY ("USER_NUMBER")
	  REFERENCES "JAVA_WEB2"."DVD_USER" ("USER_NUMBER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_REPLY
--------------------------------------------------------

  ALTER TABLE "JAVA_WEB2"."TBL_REPLY" ADD CONSTRAINT "FK_REPLY_FREE_BOARD" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "JAVA_WEB2"."BOARD" ("BOARD_NO") ENABLE;
